---
# tasks file for flaskweb
  - name: Install Flask Web
    pip:
      name: ['flask', 'flask-mysql']
      state: present
      executable: pip3

  - name: Copy Source APP
    copy:
      src: /opt/app.py
      dest: /opt/app.py
      owner: root
      group: root

  - name: Start Web Server
    shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &