---
# tasks file for flaskweb
  - name: Install Flask Web
    pip:
      name: "{{ item }}"
      state: present
      executable: pip3
      with_items:
        - flask
        - flask-mysql

  - name: Copy Source APP
    copy:
      src: app.py
      dest: /opt/app.py

  - name: Start Web Server
    shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &